#coding: utf-8

'''
Mapping Table

	0: information position
	1: Broker title published
	2: Code, Text equivalent

'''
RecuperoInfo=[
	[1,"Status",[
						[0, "Off"],
						[1, "Checking hot or cold"],
						[2, "Cleaning cold"],
						[3, "Loading Pellets Cold"],
						[4, "Start 1 Cold"],
						[5, "Start 2 Cold"],
						[6, "Cleaning Hot"],
						[7, "Loading Pellets Hot"],
						[8, "Start 1 Hot"],
						[9, "Start 2 Hot"],
						[10, "Stabilising"],
						[11, "Power 1"],
						[12, "Power 2"],
						[13, "Power 3"],
						[14, "Power 4"],
						[15, "Power 5"],
						[30, "Diagnostics"],
						[31, "On"],
						[40, "Extinguish"],
						[41, "Cooling"],
						[42, "Cleaning Low"],
						[43, "Cleaning High"],
						[44, "Unlocking Worm Screw"],
						[45, "Auto Eco"],
						[46, "Standby"],
						[48, "Diagnostics"],
						[49, "Loading Auger"],
						[50, "Error A01 - Ignition failed"],
						[51, "Error A02 - No flame"],
						[52, "Error A03 - Tank overheating"],
						[53, "Error A04 - Flue gas temperature too high"],
						[54, "Error A05 - Duct obstruction - Wind"],
						[55, "Error A06 - Bad draft"],
						[56, "Error A09 - Flue gas probe failure"],
						[57, "Error A11 - Gear motor failure"],
						[58, "Error A13 - Motherboard temperature too high"],
						[59, "Error A14 - Active fault"],
						[60, "Error A18 - Water temperature too high"],
						[61, "Error A19 - Water temperature sensor fault"],
						[62, "Error A20 - Auxiliary probe fault"],
						[63, "Error A21 - Pressure switch alarm"],
						[64, "Error A22 - Ambient probe fault"],
						[65, "Error A23 - Brazier closing fault"],
						[66, "Error A12 - Gear motor controller failure"],
						[67, "Error A17 - Worm screw jam"],
						[69, "Waiting for security alarms"],
						]],
	[2,"Room fan status",[
										[0, "Deactivated"],
										[1, "Level 1"],
										[2, "Level 2"],
										[3, "Level 3"],
										[4, "Level 4"],
										[5, "Level 5"],
										[6, "Automatic"],
										]],
	[3,"Ducted fan 1 status",[
										[0, "Deactivated"],
										[1, "Level 1"],
										[2, "Level 2"],
										[3, "Level 3"],
										[4, "Level 4"],
										[5, "Level 5"],
										[6, "Automatic"],
										]],
	[4,"Ducted fan 2 status",[
										[0, "Deactivated"],
										[1, "Level 1"],
										[2, "Level 2"],
										[3, "Level 3"],
										[4, "Level 4"],
										[5, "Level 5"],
										[6, "Automatic"],
										]],
	[5,"Flue gas temperature"],
	[6,"Ambient temperature"],
	[7,"Puffer temperature"],
	[8,"Boiler temperature"],
	[9,"NTC3 temperature"],
	[10,"Flame status"],
	[11,"ACTIVE - Set"],
	[12,"RPM - Smoke fan"],
	[13,"RPM - Worm screw - SET"],
	[14,"RPM - Worm screw - LIVE"],
	[15,"3WayValve"], # 1== Sani, else Risc
	[16, "Pump PWM"],
	[17, "Brazier"], # 0 = Ok, !=0 = CLR
	[18, "Profile"], # 0, 10 = Manual, 1 & 11 = Dynamic, Overnight, Comfort, Power   
	[19, "Modbus_Address"],
	[20,"Active mode status"],  #0: Deactivate, 1: Active
	[21,"ACTIVE - Live"],
	[22,"Control mode",[
								[0, "Manual"],
								[1, "Dynamic"],
								]],
	[23,"Eco mode"],
	[24,"Silent mode"],
	[25,"Thermostat mode"],
	[26,"Temperature set"],
	[27,"Boiler temperature set"],
	[28,"Motherboard temperature"],
	[29,"Power level",[
							[11, "Level 1"],
							[12, "Level 2"],
							[13, "Level 3"],
							[14, "Level 4"],
							[15, "Level 5"],
							]],
	[30,"Firmware Version"],
	[31,"Database ID"],
	[32,"Date_Time_Hours (0-23)"],
	[33,"Date_Time_Minutes (0-29)"],
	[34,"Date_Day_Of_Month (1-31)"],
	[35,"Date_Month (1-12)"],
	[36,"Date_Year"],
	[37,"Total_Operating_Hours (s)"],
	[38,"Hours in Power Level 1 (s)"],
	[39,"Hours in Power Level 2 (s)"],
	[40,"Hours in Power Level 3 (s)"],
	[41,"Hours in Power Level 4 (s)"],
	[42,"Hours in Power Level 5 (s)"],
	[43,"Hours to service"],
	[44,"Minutes to turn off"],
	[45,"Number of ignitions"],
	[46, "Active Temperature"],
	[47, "Celcius Or Fahrenheit"],
	[48, "Sound Effects"],
	[49, "Sound Effects State"],
	[50, "Sleep"],
	[51,"Mode",[
				[0, "Winter"],
				[1, "Summer"],
				]],
	],
	[52, "WiFi Prode temperature 1"],
	[53, "WiFi Prode temperature 2"],
	[54, "WiFi Prode temperature 3"],
	[56, "Set Puffer"],
	[57, "Set Boiler"],
	[58, "Se Health"],  # != 255 == Hydro version
	[59, "Return Temperature"],
	[60, "AntiFreeze"]
